version: '3.5'
services:
  web:
    build: .
    ports:
      - '3001:80'

  test-lint:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run lint

  test-unit-integration:
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=development
      - TZ=Europe/Amsterdam
    command: npm run test
